package com.wimoor.amazon.product.pojo.vo;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
@Data
@ApiModel(value="AmzProductListVo对象", description="商品列表")
public class AmzProductListVo {
	String id;
	String msku;
	String invalid;
	String mid;
	String asin;
	String sku;
	String marketplaceid;
	String groupid;
	String pointName;
	String name;
	String parentAsin;
	String skucolor;
	String opendate;
	String fulfillchannel;
	String binding;
	String region;
	String mregion;
	String manufacturer;
	Integer totalOfferCount;
	Integer followcount;
	Integer notread;
	String pgroup;
	String typename;
	String image;
	String country;
	BigDecimal landedAmount;
	String landedCurrency;
	Integer afnFulfillableQuantity;
	String amazonAuthId;
	String listingCurrency;
	boolean isparent;
	boolean disable;
	boolean isread;
	boolean negative;
	boolean haslocked;
	boolean itemshow;
	Integer flownnumber;
	BigDecimal averageSalesDay;
	BigDecimal averageSalesWeek;
	BigDecimal averageSalesMonth;
	BigDecimal sumweek;
	BigDecimal orderweek;
	BigDecimal sales15;
	BigDecimal sessionrate;
	BigDecimal advimpr ;
	BigDecimal advclick ;
	BigDecimal advsales ;
	BigDecimal advspend ;
	BigDecimal sessions  ;
	BigDecimal advcpc  ;
	BigDecimal advctr  ;
	BigDecimal advacos  ;
	BigDecimal advspc  ;
	BigDecimal prorate  ;
	BigDecimal proprate  ;
	BigDecimal acoas  ;
	BigDecimal profits  ;
	BigDecimal othercost  ;
	BigDecimal profitall  ;
	BigDecimal summonth  ;
	BigDecimal priceweek;
	BigDecimal profitrate;
	String newprorate;
	Integer ordermonth;
	Integer rank  ;
	Integer feedbackCount;
	Integer fulfillquantity;
	Integer optstatus;
	Integer marketindex;
	Integer countryinv;
	Integer czinv;
	BigDecimal dayfulfilla;
	BigDecimal dayinbound;
	BigDecimal buybox;
	BigDecimal positiveFeedbackRating;
	BigDecimal changeprice;
	Integer unitsordered7;
	//Integer afn_fulfillable_quantity;
	String remark;
	String followid;
	String marketplacename;
	String groupname;
	String revid;
	String revrefreshtime;
	String optstatusname;
	String optstatuscolor;
	String priceremark;
	String tagids;
	Integer fulfillmentAvailability;
	@ApiModelProperty(value = "是否轻小")
	String inSnl;
	Date lastupdateTime;
	Date lockedtime;
	List<Map<String,Object>> tagNameList;
	
}
