/*
 * Fulfillment Inbound v2024-03-20
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.fulfillmentinboundV20240320;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * The &#x60;updateItemComplianceDetails&#x60; request.
 */
@ApiModel(description = "The `updateItemComplianceDetails` request.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2024-11-13T14:17:39.430+08:00")
public class UpdateItemComplianceDetailsRequest {
  @SerializedName("msku")
  private String msku = null;

  @SerializedName("taxDetails")
  private TaxDetails taxDetails = null;

  public UpdateItemComplianceDetailsRequest msku(String msku) {
    this.msku = msku;
    return this;
  }

   /**
   * The merchant SKU, a merchant-supplied identifier for a specific SKU.
   * @return msku
  **/
  @ApiModelProperty(required = true, value = "The merchant SKU, a merchant-supplied identifier for a specific SKU.")
  public String getMsku() {
    return msku;
  }

  public void setMsku(String msku) {
    this.msku = msku;
  }

  public UpdateItemComplianceDetailsRequest taxDetails(TaxDetails taxDetails) {
    this.taxDetails = taxDetails;
    return this;
  }

   /**
   * Get taxDetails
   * @return taxDetails
  **/
  @ApiModelProperty(required = true, value = "")
  public TaxDetails getTaxDetails() {
    return taxDetails;
  }

  public void setTaxDetails(TaxDetails taxDetails) {
    this.taxDetails = taxDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateItemComplianceDetailsRequest updateItemComplianceDetailsRequest = (UpdateItemComplianceDetailsRequest) o;
    return Objects.equals(this.msku, updateItemComplianceDetailsRequest.msku) &&
        Objects.equals(this.taxDetails, updateItemComplianceDetailsRequest.taxDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(msku, taxDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateItemComplianceDetailsRequest {\n");
    
    sb.append("    msku: ").append(toIndentedString(msku)).append("\n");
    sb.append("    taxDetails: ").append(toIndentedString(taxDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

