/*
 * Selling Partner APIs for Fulfillment Outbound
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amazon.spapi.model.fulfillmentoutbound;

import java.util.Objects;
import java.util.Arrays;
import com.amazon.spapi.model.fulfillmentoutbound.ReasonCodeDetailsList;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ListReturnReasonCodesResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-15T20:44:18.412+08:00")
public class ListReturnReasonCodesResult {
  @SerializedName("reasonCodeDetails")
  private ReasonCodeDetailsList reasonCodeDetails = null;

  public ListReturnReasonCodesResult reasonCodeDetails(ReasonCodeDetailsList reasonCodeDetails) {
    this.reasonCodeDetails = reasonCodeDetails;
    return this;
  }

   /**
   * Get reasonCodeDetails
   * @return reasonCodeDetails
  **/
  @ApiModelProperty(value = "")
  public ReasonCodeDetailsList getReasonCodeDetails() {
    return reasonCodeDetails;
  }

  public void setReasonCodeDetails(ReasonCodeDetailsList reasonCodeDetails) {
    this.reasonCodeDetails = reasonCodeDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListReturnReasonCodesResult listReturnReasonCodesResult = (ListReturnReasonCodesResult) o;
    return Objects.equals(this.reasonCodeDetails, listReturnReasonCodesResult.reasonCodeDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reasonCodeDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListReturnReasonCodesResult {\n");
    
    sb.append("    reasonCodeDetails: ").append(toIndentedString(reasonCodeDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

