/*
 * The Selling Partner API for CustomerFeedback
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * OpenAPI spec version: 2024-06-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.amazon.spapi.model.customerfeedback;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The browse node review topic metrics.
 */
@Schema(description = "The browse node review topic metrics.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-07-08T10:30:47.588079500+08:00[Asia/Shanghai]")

public class BrowseNodeReviewTrendMetrics {
  @SerializedName("occurrencePercentage")
  private BrowseNodeAllOccurrence occurrencePercentage = null;

  public BrowseNodeReviewTrendMetrics occurrencePercentage(BrowseNodeAllOccurrence occurrencePercentage) {
    this.occurrencePercentage = occurrencePercentage;
    return this;
  }

   /**
   * Get occurrencePercentage
   * @return occurrencePercentage
  **/
  @Schema(required = true, description = "")
  public BrowseNodeAllOccurrence getOccurrencePercentage() {
    return occurrencePercentage;
  }

  public void setOccurrencePercentage(BrowseNodeAllOccurrence occurrencePercentage) {
    this.occurrencePercentage = occurrencePercentage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BrowseNodeReviewTrendMetrics browseNodeReviewTrendMetrics = (BrowseNodeReviewTrendMetrics) o;
    return Objects.equals(this.occurrencePercentage, browseNodeReviewTrendMetrics.occurrencePercentage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(occurrencePercentage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BrowseNodeReviewTrendMetrics {\n");
    
    sb.append("    occurrencePercentage: ").append(toIndentedString(occurrencePercentage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
