INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('envelope_ca', 'Envelope', b'1', 'CA', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('envelope_mx', 'Envelope', b'1', 'MX', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('large_oversize_us', 'Large Oversize', b'0', 'US', 1.0000, 'Lg-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('large_standard_us', 'Large Standard-Size', b'1', 'US', 0.2500, 'Lg-Std');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('lg_envelope_au', 'Large Envelope', b'1', 'AU', 0.0250, 'Lg-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('lg_envelop_ae', 'Large Envelope', b'1', 'AE', 0.0400, 'Lg-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('lg_oversize_au', 'Large Oversize', b'0', 'AU', 0.5000, 'Lg-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('medium_oversize_us', 'Medium Oversize', b'0', 'US', 1.0000, 'Medium-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize1_jp', 'Oversize-1', b'0', 'JP', 0.1500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize2_jp', 'Oversize-2', b'0', 'JP', 0.1500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize3_jp', 'Oversize-3', b'0', 'JP', 0.1500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize4_jp', 'Oversize-4', b'0', 'JP', 0.5500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize5_jp', 'Oversize-5', b'0', 'JP', 0.7000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize6_jp', 'Oversize-6', b'0', 'JP', 1.2000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize7_jp', 'Oversize-7', b'0', 'JP', 1.2000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize8_jp', 'Oversize-8', b'0', 'JP', 1.4000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_ae', 'Oversize', b'0', 'AE', 0.2400, 'Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_ca', 'Oversize', b'0', 'CA', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_heavy_in', 'Oversize Heavy and Bulky', b'0', 'IN', 0.5000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_in', 'Oversize', b'0', 'IN', 0.5000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_jp', 'Oversize', b'0', 'JP', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_lgoverpkg', 'Large Oversize', b'0', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.2400, 'Lg-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_mx', 'Oversize', b'0', 'MX', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_sa', 'Oversize', b'0', 'SA', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_smoverpkg', 'Small Oversize', b'0', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.2400, 'Sm-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('oversize_stdoverpkg', 'Standard Oversize', b'0', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.2400, 'Std-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('small', 'Small', b'1', 'JP', 0.0500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_envelop_ae', 'Small Envelope', b'1', 'AE', 0.0200, 'Sm-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_envelop_au', 'Small Envelope', b'1', 'AU', 0.0250, 'Sm-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_in', 'Small Size', b'1', 'IN', 0.0800, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_de_ex_lg', 'Extra Large Letter', b'1', 'DE', 25.0000, 'Extra-Lg-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_de_lg', 'Large Letter', b'1', 'DE', 25.0000, 'Lg-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_de_sml', 'Small Letter', b'1', 'DE', 8.0000, 'Sm-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_es_lg', 'Large Letter', b'1', 'ES', 31.0000, 'Lg-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_fr_lg', 'Large Letter', b'1', 'FR', 31.0000, 'Lg-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_it_lg', 'Large Letter', b'1', 'IT', 25.0000, 'Lg-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_jp', 'Small and Light', b'1', 'JP', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_uk_lg', 'Large Letter', b'1', 'UK', 25.0000, 'Lg-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_uk_sml', 'Small Letter', b'1', 'UK', 8.0000, 'Sm-Ltr');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_light_us', 'Small and Light', b'1', 'US', 0.7000, 'Small and Light');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_oversize_au', 'Small Oversize', b'0', 'AU', 0.5000, 'Sm-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_oversize_us', 'Small Oversize', b'0', 'US', 1.0000, 'Sm-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('sml_standard_us', 'Small Standard-Size', b'1', 'US', 0.2500, 'Sm-Std');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('special_ca', 'Special Oversize', b'0', 'CA', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('special_oversize_us', 'Special Oversize', b'0', 'US', 1.0000, 'Special-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('standard', 'Standard', b'1', 'JP', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std1_jp', 'Standard-1', b'1', 'JP', 0.0500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std2_jp', 'Standard-2', b'1', 'JP', 0.1500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std3_jp', 'Standard-3', b'1', 'JP', 0.1500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std4_jp', 'Standard-4', b'1', 'JP', 0.1500, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_ca', 'Standard-Size', b'1', 'CA', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_envelope_au', 'Standard Envelope', b'1', 'AU', 0.0250, 'Std-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_envelop_ae', 'Standard Envelope', b'1', 'AE', 0.0400, 'Std-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_in', 'Standard Size', b'1', 'IN', 0.1000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_lgpkg', 'Large Envelope Standard-Size', b'1', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.0400, 'Lg-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_mx', 'Standard Size', b'1', 'MX', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_oversize_au', 'Standard Oversize', b'0', 'AU', 0.5000, 'Std-Oversize');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_parcel_ae', 'Standard Parcel', b'1', 'AE', 0.1000, 'Std-Parcel');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_parcel_au', 'Standard parcel', b'1', 'AU', 0.1250, 'Std-Parcel');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_sa', 'Standard Size', b'1', 'SA', NULL, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_smpkg', 'Small Envelope Standard-Size', b'1', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.0200, 'Sm-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_stdpkg', 'Standard Parcel Standard-Size', b'1', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.1000, 'Std-Parcel');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('std_stdpkg_box', 'Standard Envelope Standard-Size', b'1', 'UK,DE,FR,IT,ES,NL,PL,SE', 0.0400, 'Std-Env');
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('supersize1_jp', 'Supersize-1', b'0', 'JP', 1.4000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('supersize2_jp', 'Supersize-2', b'0', 'JP', 1.5000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('supersize3_jp', 'Supersize-3', b'0', 'JP', 1.7000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('supersize4_jp', 'Supersize-4', b'0', 'JP', 1.8000, NULL);
INSERT INTO `t_producttier` (`id`, `name`, `isStandard`, `country`, `box_weight`, `amz_name`) VALUES ('supersize_jp', 'Supersize', b'0', 'JP', NULL, NULL);
