-- --------------------------------------------------------
-- 主机:                           wimoor.rwlb.rds.aliyuncs.com
-- 服务器版本:                        8.0.36 - Source distribution
-- 服务器操作系统:                      Linux
-- HeidiSQL 版本:                  12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- 正在导出表  db_amazon.t_amz_settlement_amount_description 的数据：~115 rows (大约)
DELETE FROM `t_amz_settlement_amount_description`;
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES
	(1, '佣金', 'Commission', '针对所售商品价值收取的费用', 'Fee charged against the value of the item sold.'),
	(2, 'FBA每件处理费', 'FBAPerUnitFulfilmentFee', '为了补偿亚马逊的配送成本而对每件商品收取的费用', 'Per-unit fee charged to compensate Amazon for the cost of fulfilling.'),
	(3, 'FBA基于重量的处理费', 'FBAWeightBasedFee', '为了补偿亚马逊的配送成本而对每个订单向亚马逊物流卖家收取的费用', 'Fee assessed for FBA sellers on a per-item basis to compensate Amazon for the cost of shipping per order.'),
	(4, '信用卡拒付(礼品包装)', 'GiftwrapChargeback', '针对亚马逊物流商品收取的礼品包装费是您总销售收益的一部分。我们将其作为收益（参见礼品', 'Giftwrap charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as revenue (see Giftwrap) and charge you a GiftwrapChargeback fee equal to the amounts charged to the customer.'),
	(5, '退款佣金', 'RefundCommission', '当发放退款时，针对退还的原始费用金额所收取的费用', 'When a refund is issued, the fee charged against the original fee amount being refunded.'),
	(6, '信用卡拒付(配送费)', 'DeliveryChargeback', '针对亚马逊物流商品收取的运费是您总销售收益的一部分。我们将其作为收益（参见运费）向您', 'Shipping charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as revenue (see Shipping) and charge you a ShippingChargeback fee equal to the amounts charged to the customer.'),
	(7, '变动结算费', 'VariableClosingFee', '针对商品销售收取的非固定交易手续费。有关详细信息，请参见 我要开店 费用价目表 。', 'Variable closing fee charge for the sale of an item. Refer to the Selling on Amazon Fee Schedule for more details.'),
	(8, '礼品包装费', 'GiftWrap', '针对亚马逊物流商品收取的礼品包装费是您总销售收益的一部分。我们将其作为礼品包装收益向', 'Giftwrap charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as Giftwrap revenue and charge you a fee (see GiftwrapChargeback) equal to the amounts charged to the customer.'),
	(9, '商誉费', 'Goodwill', '买家退款，不适用于特定费用', 'Customer refund, not applied against a specific charge.'),
	(10, '本金', 'Principal', '向买家收取（或退还）的商品金额', 'Amount charged (or refunded) to customer for item.'),
	(11, '重新入库费', 'RestockingFee', '对于不符合全额退款条件的退货，可能向买家收取重新入库费。将买家退款的盘点报告为卖家存', 'Customers may be charged a RestockingFee for returns that are not eligible for a full refund. This adjustment to the customer\'s refund is reported as a seller credit.'),
	(12, '配送费', 'Delivery', '针对亚马逊物流商品收取的运费是您总销售收益的一部分。我们将其作为运费收益向您报告并向', 'Shipping charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as Shipping revenue and charge you a fee (see ShippingChargeback) equal to the amounts charged to the customer.'),
	(13, '当前预留金额', 'Current Reserve Amount', '预留金额是结算周期内保留的金额，以支付预期费用，例如退货和退款', 'The reserve amount is the amount held back in a settlement period to cover potential expenses such as returns and refunds.'),
	(14, '上一期预留金', 'Previous Reserve Amount Balance', '以前结算报告上的预留金额', 'The reserve amount from the previous settlement report.'),
	(15, '退款补偿', 'Refund Reimbursal', '针对买家退款向卖家收取的偿还金额', 'Reimbursal of amount charged to seller for customer refund.'),
	(16, '仓储费', 'Storage Fee', '针对存储在亚马逊库房的卖家商品收取的仓储费用', 'Storage fee for seller\'s items stored in Amazon\'s warehouse.'),
	(17, 'FBA订单处理费', 'FBAPerOrderFulfilmentFee', '为了补偿亚马逊的配送成本而对每个订单收取的费用', 'Per-order fee charged to compensate Amazon for the cost of fulfilling per order.'),
	(18, 'FBA运输费(FBA MCF)', 'FBATransportationFee', '为了补偿亚马逊的配送成本而对每个订单收取的亚马逊物流多渠道配送费', 'Fee assessed for FBA Multi-Channel Fulfillment to compensate Amazon for the cost of shipping per order.'),
	(19, '配送', 'Shipping', '应用于合格订单的运费促销折扣。', 'Shipping promotion applied to qualifying orders.'),
	(20, '税费', 'Tax', '', ''),
	(21, '平台服务税(订单总额)', 'MarketplaceFacilitatorTax-Principal', '', ''),
	(22, '平台服务税(运费)', 'MarketplaceFacilitatorTax-Shipping', '', ''),
	(23, '低值品本金', 'LowValueGoods-Principal', '', ''),
	(24, '低值品配送费', 'LowValueGoods-Shipping', '', ''),
	(25, '运费税额', 'ShippingTax', '', ''),
	(26, '礼品包装费税', 'Gift Wrap Tax', '', ''),
	(28, '信用卡拒付(礼品包装-CGST)', 'Gift Wrap Chargeback CGST', '', ''),
	(29, '信用卡拒付(礼品包装-SGST)', 'Gift Wrap Chargeback SGST', '', ''),
	(30, '信用卡拒付(礼品包装)', 'Gift Wrap Chargeback', '', ''),
	(32, '秒杀费', 'LightningDealFee', '', ''),
	(33, '固定结算费', 'Fixed closing fee', '', ''),
	(34, '移除库存费', 'RemovalComplete', '', ''),
	(35, '退款佣金IGST', 'Refund commission IGST', '', ''),
	(36, '交易总额', 'TransactionTotalAmount', '', ''),
	(37, '税务折扣', 'TaxDiscount', '', ''),
	(38, '信用卡拒付(运费)', 'Shipping Chargeback', '', ''),
	(41, '秒杀费', 'LightningDealFee Special', '', ''),
	(42, '货到付款费用', 'CODFee', '', ''),
	(43, '货到付款税', 'COD Tax', '', ''),
	(44, '货到付款', 'COD', '', ''),
	(45, '弃置库存费', 'DisposalComplete', '', ''),
	(46, 'FBA重量处理费SGST', 'FBA Weight Handling Fee SGST', '', ''),
	(47, '产品税', 'Product Tax', '', ''),
	(49, '订阅费', 'Subscription Fee', '', ''),
	(51, '信用卡拒付(运费-CGST)', 'Shipping Chargeback CGST', '', ''),
	(52, '信用卡拒付(运费-SGST)', 'Shipping Chargeback SGST', '', ''),
	(53, '运费折扣', 'Shipping discount', '', ''),
	(54, '运输税', 'Shipping tax', '', ''),
	(55, '运输税折扣', 'Shipping tax discount', '', ''),
	(56, '信用卡拒付(运费)', 'ShippingChargeback', '', ''),
	(59, '入库丢失', 'MISSING_FROM_INBOUND', '', ''),
	(60, '授予的点', 'PointsGranted', '', ''),
	(64, '余额调整', 'BalanceAdjustment', '亚马逊因某项计算错误而对卖家的余额进行调整(增加或扣减)', ''),
	(65, 'FBA 顾客退货管理费', 'FBACustomerReturn', '', ''),
	(66, '亚马逊资金服务费', 'Amazon Capital Services', '', ''),
	(67, '邮资调整费', 'PostageAdjustment', '', ''),
	(68, 'FBA 入仓\r\n缺陷费', 'FBAInboundDefectFee', '', ''),
	(69, '标签问题', 'LABEL_ISSUE', '', ''),
	(70, '库存更新费用', 'StorageRenewalBilling', '', ''),
	(71, 'FBA 处理费', 'FBADisposalFee', '', ''),
	(72, 'FBA 移除费', 'FBARemovalFee', '', ''),
	(73, '检货及包货费用', 'Pick Pack Fees', '', ''),
	(74, 'FBA重量处理费', 'Weight Handling Fees', '', ''),
	(75, '固定结算费', 'FixedClosingFee', '', ''),
	(76, '多袋包装费', 'PolybaggingFee ', '', ''),
	(80, '一般费用', 'Recurring Fees', '所有未归类到订单类的，支付给亚马逊的费用', ''),
	(81, '标签费', 'LabelingFee', '', ''),
	(82, '单件超期仓储费', 'SSOFFFulfillmentFee', '', 'There is a minimum charge of $0.50 per unit per month for items that have been in a fulfillment center for more than 365 days. Either the long-term storage fee or the minimum fee will apply, whichever is greater. For more information, see FBA long-term storage fees '),
	(83, '礼品包装费用税额', 'GiftWrapTax', '', ''),
	(84, '平台服务税(其他)', 'MarketplaceFacilitatorTax-Other', '', ''),
	(85, '库存配置费', 'Inventory Placement Service Fee', '', ''),
	(86, '额外的退货费', 'FBACustomerReturnPerUnitFee', '', ''),
	(87, '逆向偿付', 'REVERSAL_REIMBURSEMENT', '', ''),
	(88, '退款管理费用', 'RefundAdministration Fee', '', ''),
	(89, '大批量商品费用', 'HighVolume Listing Fee', '', ''),
	(90, '长期储存费用', 'FBA Long-Term Storage', '', ''),
	(91, '移除订单费用', 'FBA removal order fees', '', ''),
	(92, '多渠道配送订单的配送费用', 'FulfillmentFees for Multi-Channel Fulfillment Orders', '', ''),
	(93, '促销', 'Promotion', '', ''),
	(94, '运费', 'DispatchFees', '', ''),
	(95, '其他交易', 'other-transaction', '', ''),
	(96, '商品价格', 'ItemPrice', '', ''),
	(97, '商品费用', 'ItemFees', '', ''),
	(99, '广告费用', 'Cost of Advertising', '', ''),
	(100, '折扣劵兑换费', 'CouponRedemptionFee', '当买家使用卖家设置的折扣券购物时,亚马逊对卖家使用平台的折扣券促销方式收取的费用', ''),
	(101, '订单', 'Order', '', ''),
	(103, '退款', 'Refund', '', ''),
	(104, '服务费', 'ServiceFee', '', ''),
	(105, '秒杀费', 'Lightning Deal Fee', '', ''),
	(106, '\r\n退款回收', 'Refund_Retrocharge', '', ''),
	(107, '订单退回款', 'Order_Retrocharge', '', ''),
	(108, '信用卡拒付(退款)', 'Chargeback Refund', '', ''),
	(109, '卖家重审付款', 'SellerReviewEnrollmentPayment', '', ''),
	(115, '低价值商品税(运费)', 'LowValueGoodsTax-Shipping', '', ''),
	(116, '仓储损毁赔偿', 'WAREHOUSE_DAMAGE', '', ''),
	(117, '仓储丢失赔偿', 'WAREHOUSE_LOST', '', ''),
	(118, '平台服务税(重新入库)', 'MarketplaceFacilitatorTax-RestockingFee', '', ''),
	(119, 'FBA订单处理费', 'FBAPerOrderFulfillmentFee', '', ''),
	(120, '赔偿撤回', 'COMPENSATED_CLAWBACK', '', ''),
	(121, '低价值商品税(订单)', 'LowValueGoodsTax-Principal', '', ''),
	(122, 'FBA每件处理费', 'FBAPerUnitFulfillmentFee', '', ''),
	(123, '早期评论者计划费用', 'Early Reviewer Program fee', '', ''),
	(124, '运费折扣', 'ShippingCharge', '', ''),
	(125, '促销折扣金额', 'PromotionMetaDataDefinitionValue', '', ''),
	(126, '亚马逊物流国际货运费（头程运费）', 'FBA International Freight Shipping Charge', '', ''),
	(127, '上期转账失败入账金额', 'Transfer of funds unsuccessful: Amazon has cancelled your transfer of funds.', '', ''),
	(128, '成功收费交易', 'Successful charge', '本次账期中对于亚马逊的欠款（即您欠亚马逊50元，亚马逊说我先给你垫付）', ''),
	(129, '应付亚马逊金额', 'Payable to Amazon', '上次亚马逊给你垫了钱，这次要从账期里面扣掉', ''),
	(130, '错误赔付', 'INCORRECT_FEES_ITEMS', '即亚马逊因为错误的长宽高等原有多收取了您的费用，进行赔付', ''),
	(131, '待扣税款', 'ItemWithheldTax', '', ''),
	(132, '清算调整', 'Liquidations Adjustments', '', ''),
	(133, '清算', 'Liquidations', '', ''),
	(134, '费用调整', 'Fee Adjustment', '', ''),
	(135, '清算经济费(中间费用)', 'LiquidationsBrokerageFee', '', ''),
	(136, '仓库损坏赔偿', 'FBA Inventory Reimbursement', '', '');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
