INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (1, '佣金', 'Commission', '针对所售商品价值收取的费用', 'Fee charged against the value of the item sold.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (2, 'FBA每件处理费', 'FBAPerUnitFulfilmentFee', '为了补偿亚马逊的配送成本而对每件商品收取的费用', 'Per-unit fee charged to compensate Amazon for the cost of fulfilling.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (3, 'FBA基于重量的处理费', 'FBAWeightBasedFee', '为了补偿亚马逊的配送成本而对每个订单向亚马逊物流卖家收取的费用', 'Fee assessed for FBA sellers on a per-item basis to compensate Amazon for the cost of shipping per order.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (4, '信用卡拒付(礼品包装)', 'GiftwrapChargeback', '针对亚马逊物流商品收取的礼品包装费是您总销售收益的一部分。我们将其作为收益（参见礼品', 'Giftwrap charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as revenue (see Giftwrap) and charge you a GiftwrapChargeback fee equal to the amounts charged to the customer.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (5, '退款佣金', 'RefundCommission', '当发放退款时，针对退还的原始费用金额所收取的费用', 'When a refund is issued, the fee charged against the original fee amount being refunded.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (6, '信用卡拒付(配送费)', 'DeliveryChargeback', '针对亚马逊物流商品收取的运费是您总销售收益的一部分。我们将其作为收益（参见运费）向您', 'Shipping charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as revenue (see Shipping) and charge you a ShippingChargeback fee equal to the amounts charged to the customer.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (7, '变动结算费', 'VariableClosingFee', '针对商品销售收取的非固定交易手续费。有关详细信息，请参见 我要开店 费用价目表 。', 'Variable closing fee charge for the sale of an item. Refer to the Selling on Amazon Fee Schedule for more details.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (8, '礼品包装费', 'GiftWrap', '针对亚马逊物流商品收取的礼品包装费是您总销售收益的一部分。我们将其作为礼品包装收益向', 'Giftwrap charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as Giftwrap revenue and charge you a fee (see GiftwrapChargeback) equal to the amounts charged to the customer.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (9, '商誉费', 'Goodwill', '买家退款，不适用于特定费用', 'Customer refund, not applied against a specific charge.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (10, '本金', 'Principal', '向买家收取（或退还）的商品金额', 'Amount charged (or refunded) to customer for item.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (11, '重新入库费', 'RestockingFee', '对于不符合全额退款条件的退货，可能向买家收取重新入库费。将买家退款的盘点报告为卖家存', 'Customers may be charged a RestockingFee for returns that are not eligible for a full refund. This adjustment to the customer\'s refund is reported as a seller credit.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (12, '配送费', 'Delivery', '针对亚马逊物流商品收取的运费是您总销售收益的一部分。我们将其作为运费收益向您报告并向', 'Shipping charges for Amazon Fulfilled units are part of your gross sales proceeds. We report them to you as Shipping revenue and charge you a fee (see ShippingChargeback) equal to the amounts charged to the customer.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (13, '当前预留金额', 'Current Reserve Amount', '预留金额是结算周期内保留的金额，以支付预期费用，例如退货和退款', 'The reserve amount is the amount held back in a settlement period to cover potential expenses such as returns and refunds.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (14, '上一期预留金', 'Previous Reserve Amount Balance', '以前结算报告上的预留金额', 'The reserve amount from the previous settlement report.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (15, '退款补偿', 'Refund Reimbursal', '针对买家退款向卖家收取的偿还金额', 'Reimbursal of amount charged to seller for customer refund.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (16, '仓储费', 'Storage Fee', '针对存储在亚马逊库房的卖家商品收取的仓储费用', 'Storage fee for seller\'s items stored in Amazon\'s warehouse.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (17, 'FBA订单处理费', 'FBAPerOrderFulfilmentFee', '为了补偿亚马逊的配送成本而对每个订单收取的费用', 'Per-order fee charged to compensate Amazon for the cost of fulfilling per order.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (18, 'FBA运输费(FBA MCF)', 'FBATransportationFee', '为了补偿亚马逊的配送成本而对每个订单收取的亚马逊物流多渠道配送费', 'Fee assessed for FBA Multi-Channel Fulfillment to compensate Amazon for the cost of shipping per order.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (19, '配送', 'Shipping', '应用于合格订单的运费促销折扣。', 'Shipping promotion applied to qualifying orders.');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (20, '税费', 'Tax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (21, '平台服务税(订单总额)', 'MarketplaceFacilitatorTax-Principal', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (22, '平台服务税(运费)', 'MarketplaceFacilitatorTax-Shipping', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (23, '低值品本金', 'LowValueGoods-Principal', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (24, '低值品配送费', 'LowValueGoods-Shipping', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (25, '运费税额', 'ShippingTax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (26, '礼品包装费税', 'Gift Wrap Tax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (28, '信用卡拒付(礼品包装-CGST)', 'Gift Wrap Chargeback CGST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (29, '信用卡拒付(礼品包装-SGST)', 'Gift Wrap Chargeback SGST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (30, '信用卡拒付(礼品包装)', 'Gift Wrap Chargeback', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (32, '秒杀费', 'LightningDealFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (33, '固定结算费', 'Fixed closing fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (34, '移除库存费', 'RemovalComplete', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (35, '退款佣金IGST', 'Refund commission IGST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (36, '交易总额', 'TransactionTotalAmount', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (37, '税务折扣', 'TaxDiscount', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (38, '信用卡拒付(运费)', 'Shipping Chargeback', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (41, '秒杀费', 'LightningDealFee Special', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (42, '货到付款费用', 'CODFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (43, '货到付款税', 'COD Tax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (44, '货到付款', 'COD', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (45, '弃置库存费', 'DisposalComplete', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (46, 'FBA重量处理费SGST', 'FBA Weight Handling Fee SGST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (47, '产品税', 'Product Tax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (49, '订阅费', 'Subscription Fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (51, '信用卡拒付(运费-CGST)', 'Shipping Chargeback CGST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (52, '信用卡拒付(运费-SGST)', 'Shipping Chargeback SGST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (53, '运费折扣', 'Shipping discount', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (54, '运输税', 'Shipping tax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (55, '运输税折扣', 'Shipping tax discount', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (56, '信用卡拒付(运费)', 'ShippingChargeback', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (59, '入库丢失', 'MISSING_FROM_INBOUND', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (60, '授予的点', 'PointsGranted', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (64, '余额调整', 'BalanceAdjustment', '亚马逊因某项计算错误而对卖家的余额进行调整(增加或扣减)', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (65, 'FBA 顾客退货管理费', 'FBACustomerReturn', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (66, '亚马逊资金服务费', 'Amazon Capital Services', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (67, '邮资调整费', 'PostageAdjustment', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (68, 'FBA 入仓\r\n缺陷费', 'FBAInboundDefectFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (69, '标签问题', 'LABEL_ISSUE', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (70, '库存更新费用', 'StorageRenewalBilling', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (71, 'FBA 处理费', 'FBADisposalFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (72, 'FBA 移除费', 'FBARemovalFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (73, '检货及包货费用', 'Pick Pack Fees', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (74, 'FBA重量处理费', 'Weight Handling Fees', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (75, '固定结算费', 'FixedClosingFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (76, '多袋包装费', 'PolybaggingFee ', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (80, '一般费用', 'Recurring Fees', '所有未归类到订单类的，支付给亚马逊的费用', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (81, '标签费', 'LabelingFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (82, '单件超期仓储费', 'SSOFFFulfillmentFee', '', 'There is a minimum charge of $0.50 per unit per month for items that have been in a fulfillment center for more than 365 days. Either the long-term storage fee or the minimum fee will apply, whichever is greater. For more information, see FBA long-term storage fees ');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (83, '礼品包装费用税额', 'GiftWrapTax', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (84, '平台服务税(其他)', 'MarketplaceFacilitatorTax-Other', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (85, '库存配置费', 'Inventory Placement Service Fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (86, '额外的退货费', 'FBACustomerReturnPerUnitFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (87, '逆向偿付', 'REVERSAL_REIMBURSEMENT', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (88, '退款管理费用', 'RefundAdministration Fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (89, '大批量商品费用', 'HighVolume Listing Fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (90, '长期储存费用', 'FBA Long-Term Storage', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (91, '移除订单费用', 'FBA removal order fees', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (92, '多渠道配送订单的配送费用', 'FulfillmentFees for Multi-Channel Fulfillment Orders', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (93, '促销', 'Promotion', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (94, '运费', 'DispatchFees', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (95, '其他交易', 'other-transaction', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (96, '商品价格', 'ItemPrice', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (97, '商品费用', 'ItemFees', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (99, '广告费用', 'Cost of Advertising', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (100, '折扣劵兑换费', 'CouponRedemptionFee', '当买家使用卖家设置的折扣券购物时,亚马逊对卖家使用平台的折扣券促销方式收取的费用', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (101, '订单', 'Order', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (103, '退款', 'Refund', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (104, '服务费', 'ServiceFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (105, '秒杀费', 'Lightning Deal Fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (106, '\r\n退款回收', 'Refund_Retrocharge', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (107, '订单退回款', 'Order_Retrocharge', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (108, '信用卡拒付(退款)', 'Chargeback Refund', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (109, '卖家重审付款', 'SellerReviewEnrollmentPayment', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (115, '低价值商品税(运费)', 'LowValueGoodsTax-Shipping', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (116, '仓储损毁赔偿', 'WAREHOUSE_DAMAGE', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (117, '仓储丢失赔偿', 'WAREHOUSE_LOST', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (118, '平台服务税(重新入库)', 'MarketplaceFacilitatorTax-RestockingFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (119, 'FBA订单处理费', 'FBAPerOrderFulfillmentFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (120, '赔偿撤回', 'COMPENSATED_CLAWBACK', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (121, '低价值商品税(订单)', 'LowValueGoodsTax-Principal', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (122, 'FBA每件处理费', 'FBAPerUnitFulfillmentFee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (123, '早期评论者计划费用', 'Early Reviewer Program fee', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (124, '运费折扣', 'ShippingCharge', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (125, '促销折扣金额', 'PromotionMetaDataDefinitionValue', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (126, '亚马逊物流国际货运费（头程运费）', 'FBA International Freight Shipping Charge', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (127, '上期转账失败入账金额', 'Transfer of funds unsuccessful: Amazon has cancelled your transfer of funds.', '', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (128, '成功收费交易', 'Successful charge', '本次账期中对于亚马逊的欠款（即您欠亚马逊50元，亚马逊说我先给你垫付）', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (129, '应付亚马逊金额', 'Payable to Amazon', '上次亚马逊给你垫了钱，这次要从账期里面扣掉', '');
INSERT INTO `t_amz_settlement_amount_description` (`id`, `cname`, `ename`, `cdescription`, `edescription`) VALUES (130, '错误赔付', 'INCORRECT_FEES_ITEMS', '即亚马逊因为错误的长宽高等原有多收取了您的费用，进行赔付', '');
