-- --------------------------------------------------------
-- 主机:                           wimoor.rwlb.rds.aliyuncs.com
-- 服务器版本:                        8.0.36 - Source distribution
-- 服务器操作系统:                      Linux
-- HeidiSQL 版本:                  12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- 正在导出表  db_amazon.t_marketplace 的数据：~23 rows (大约)
DELETE FROM `t_marketplace`;
INSERT INTO `t_marketplace` (`marketplaceId`, `market`, `name`, `region_name`, `region`, `end_point`, `point_name`, `accessKey`, `secretKey`, `dim_units`, `weight_units`, `currency`, `findex`, `adv_end_point`, `aws_access_key`, `aws_secret_key`, `associate_tag`, `developer_url`, `dev_account_num`, `bytecode`, `sp_api_endpoint`, `aws_region`, `language`) VALUES
	('A13V1IB3VIYZZH', 'FR', '法国', '欧洲', 'EU', 'https://mws.amazonservices.fr', 'Amazon.fr', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 5, 'webservices.amazon.fr', 'AKIAJDEDZE4WEBE3IHVA', 's9aMvcsBm/5NsxVUuI8i4e6OACRVhwhJt/gbG+FN', 'kuuqastore-21', 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'fr_FR'),
	('A17E79C6D8DWNP', 'SA', '沙特', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Amazon.sa', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'SAR', 17, NULL, NULL, NULL, NULL, 'https://sellercentral.amazon.sa/gp/help/external/help.html?itemID=201112670&language=en_AE&ref=ag_201112670_cont_200209150&initialSessionID=261-8517588-7951024&ld=ASSAFBADirect', '9000-8766-5178', 'UTF-8', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'ar_SA'),
	('A1805IZSGTT6HS', 'NL', '荷兰', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Amazon.nl', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 16, NULL, NULL, NULL, NULL, 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'nl_NL'),
	('A19VAU5U5O7RUS', 'SG', '新加坡', '远东', 'SG', '	https://mws-fe.amazonservices.com', 'Amazon.sg', 'AKIAIH5YSYCVHNSGEJ5A', 'GBoWBAz0U2CEFV5DAruuebgYhNQIqwqjfSUNphAp', NULL, NULL, 'SGD', 16, NULL, NULL, NULL, NULL, NULL, '3484-6862-2072', 'UTF-8', 'https://sellingpartnerapi-fe.amazon.com', 'us-west-2', 'en_SG'),
	('A1AM78C64UM0Y8', 'MX', '墨西哥', '北美', 'NA', '	https://mws.amazonservices.com.mx', 'Amazon.com.mx', 'AKIAISXGPXGAQBBIZEGQ', 'qcJI3mabCkg9TvXafLtjtc7rwop6SyYW688TGl6S', 'cm', 'kg', 'MXN', 12, NULL, NULL, NULL, NULL, 'https://sellercentral.amazon.com.mx/gp/help/external/help.html?itemID=201411300&language=es_MX&ld=ELMXFBA-sellercentral.amazon.com.mx&initialSessionID=EL-sellercentral.amazon.com.mx', '2623-6518-2224', 'Latin1', 'https://sellingpartnerapi-na.amazon.com', 'us-east-1', 'es_MX'),
	('A1C3SOZRARQ6R3', 'PL', '波兰', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Amazon.pl', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'PLN', 19, NULL, NULL, NULL, NULL, NULL, '9000-8766-5178', 'UTF-8', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'pl_PL'),
	('A1F83G8C2ARO7P', 'UK', '英国', '欧洲', 'UK', 'https://mws.amazonservices.co.uk', 'Amazon.co.uk', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'GBP', 3, 'webservices.amazon.co.uk', 'AKIAJDEDZE4WEBE3IHVA', 's9aMvcsBm/5NsxVUuI8i4e6OACRVhwhJt/gbG+FN', 'kuuqastore-21', 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'en_GB'),
	('A1PA6795UKMFR9', 'DE', '德国', '欧洲', 'EU', 'https://mws.amazonservices.de', 'Amazon.de', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 4, 'webservices.amazon.de', 'AKIAJDEDZE4WEBE3IHVA', 's9aMvcsBm/5NsxVUuI8i4e6OACRVhwhJt/gbG+FN', 'kuuqastore-21', 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'de_DE'),
	('A1RKKUPIHCS9HS', 'ES', '西班牙', '欧洲', 'EU', 'https://mws.amazonservices.es', 'Amazon.es', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 6, 'webservices.amazon.es', 'AKIAJDEDZE4WEBE3IHVA', 's9aMvcsBm/5NsxVUuI8i4e6OACRVhwhJt/gbG+FN', 'kuuqastore-21', 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'es_ES'),
	('A1VC38T7YXB528', 'JP', '日本', '远东', 'JP', 'https://mws.amazonservices.jp', 'Amazon.co.jp', 'AKIAIH5YSYCVHNSGEJ5A', 'GBoWBAz0U2CEFV5DAruuebgYhNQIqwqjfSUNphAp', 'cm', 'kg', 'JPY', 8, 'webservices.amazon.co.jp', NULL, NULL, NULL, 'https://services.amazon.co.jp/services/fulfillment-by-amazon/en/fee.html', '3484-6862-2072', 'Shift_JIS', 'https://sellingpartnerapi-fe.amazon.com', 'us-west-2', 'ja_JP'),
	('A21TJRUUN4KGV', 'IN', '印度', '欧洲', 'IN', 'https://mws.amazonservices.in', 'Amazon.in', 'AKIAJJ6VKJAN4HQPIPZQ', 'TEJ90Y6vFyLdula64rudJfIY1ckh+ILVY4EC8m+J', 'cm', 'kg', 'INR', 10, 'webservices.amazon.in', NULL, NULL, 'kuuqastore-21', 'https://sellercentral.amazon.in/gp/help/external/G200651740?language=en_IN&ref=efph_G200651740_cont_200209150', '9000-8766-5178', 'UTF-8', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'en_IN'),
	('A28R8C7NBKEWEA', 'IE', '爱尔兰', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Amazon.ie', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 16, NULL, NULL, NULL, NULL, 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'ga_IE'),
	('A2EUQ1WTGCTBG2', 'CA', '加拿大', '北美', 'NA', 'https://mws.amazonservices.com', 'Amazon.ca', 'AKIAISXGPXGAQBBIZEGQ', 'qcJI3mabCkg9TvXafLtjtc7rwop6SyYW688TGl6S', 'cm', 'kg', 'CAD', 2, 'webservices.amazon.ca', NULL, NULL, NULL, 'https://sellercentral.amazon.ca/gp/help/external/201112670?language=en_CA&ref=efph_201112670_cont_201074400', '2623-6518-2224', 'UTF-8', 'https://sellingpartnerapi-na.amazon.com', 'us-east-1', 'en_CA'),
	('A2NODRKZP88ZB9', 'SE', '瑞典', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Amazon.se', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'SEK', 20, NULL, NULL, NULL, NULL, NULL, '9000-8766-5178', 'UTF-8', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'sv_SE'),
	('A2Q3Y263D00KWC', 'BR', '巴西', '北美', 'BR', 'https://mws.amazonservices.com', 'Amazon.com.br', 'AKIAISXGPXGAQBBIZEGQ', 'qcJI3mabCkg9TvXafLtjtc7rwop6SyYW688TGl6S', NULL, NULL, 'BRL', 13, NULL, NULL, NULL, NULL, NULL, '2623-6518-2224', 'Latin1', 'https://sellingpartnerapi-na.amazon.com', 'us-east-1', 'pt_BR'),
	('A2VIGQ35RCS4UG', 'AE', '阿联酋', '欧洲', 'AE', 'https://mws.amazonservices.ae', 'Amazon.ae', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'AED', 14, NULL, NULL, NULL, NULL, 'https://sellercentral.amazon.ae/gp/help/external/help.html?itemID=201112670&language=en_AE&ref=ag_201112670_cont_200209150&initialSessionID=257-4587144-1439310&ld=NSGoogle', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'ar_AE'),
	('A33AVAJ2PDY3EV', 'TR', '土耳其', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Amazon.com.tr', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', NULL, NULL, 'TRY', 15, NULL, NULL, NULL, NULL, 'https://satis.amazon.com.tr/ucretlendirme?ref_=astr_soa_rd&#fulfillment-fees', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'tr_TR'),
	('A39IBJ37TRP1C6', 'AU', '澳大利亚', '远东', 'AU', '	https://mws.amazonservices.com.au', 'Amazon.com.au', 'AKIAJNQKCADQULXZSIYQ', 'T8Lf78pHdtXKY9ohL1pQEO2/EioOiEPSd91e+bOO', 'cm', 'kg', 'AUD', 9, 'webservices.amazon.com.au', NULL, NULL, NULL, 'https://sellercentral.amazon.com.au/gp/help/external/201112670?language=zh_CN&ref=efph_201112670_cont_201074400', '3484-6862-2072', 'UTF-8', 'https://sellingpartnerapi-fe.amazon.com', 'us-west-2', 'en_AU'),
	('AAHKV2X7AFYLW', 'CN', '中国', '远东', 'CN', 'https://mws.amazonservices.com.cn', 'Amazon.cn', NULL, '', NULL, NULL, 'CNY', 11, 'webservices.amazon.cn', NULL, NULL, NULL, NULL, NULL, 'UTF-8', NULL, NULL, 'zh_CN'),
	('AMEN7PMS3EDWL', 'BE', '比利时', '欧洲', 'EU', 'https://mws.amazonservices.be', 'Amazon.com.be', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 20, NULL, NULL, NULL, NULL, 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'fr_BE'),
	('APJ6JRA9NG5V4', 'IT', '意大利', '欧洲', 'EU', 'https://mws.amazonservices.it', 'Amazon.it', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', 'cm', 'kg', 'EUR', 7, 'webservices.amazon.it', 'AKIAJDEDZE4WEBE3IHVA', 's9aMvcsBm/5NsxVUuI8i4e6OACRVhwhJt/gbG+FN', 'kuuqastore-21', 'https://services.amazon.co.uk/services/fulfilment-by-amazon/pricing.html', '9000-8766-5178', 'Latin1', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'it_IT'),
	('ARBP9OOSHTCHU', 'EG', '埃及', '欧洲', 'EU', 'https://mws-eu.amazonservices.com', 'Egypt.souq.com', 'AKIAI2YNBHCQANHWU6XA', 'VFBKmhGa6Y1H2dGWItuXv8NN2e8RVNVNzTpo56xv', NULL, NULL, 'EUR', 18, NULL, NULL, NULL, NULL, NULL, '9000-8766-5178', 'UTF-8', 'https://sellingpartnerapi-eu.amazon.com', 'eu-west-1', 'ar_EG'),
	('ATVPDKIKX0DER', 'US', '美国', '北美', 'NA', 'https://mws.amazonservices.com', 'Amazon.com', 'AKIAISXGPXGAQBBIZEGQ', 'qcJI3mabCkg9TvXafLtjtc7rwop6SyYW688TGl6S', 'in', 'lb', 'USD', 1, 'webservices.amazon.com', 'AKIAIV5ZIYTNRKFARG6A', 'CSxeX+nJxw/T/lUhOG6kLal7DisggLath+p8+oJw', 'Kuuqa20-01', 'https://sellercentral.amazon.com/gp/help/external/201112670?language=en_US', '2623-6518-2224', 'Latin1', 'https://sellingpartnerapi-na.amazon.com', 'us-east-1', 'en_US');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
